spring.application.name=travelwithai-api-gateway
server.port=7000
spring.docker.compose.enabled=false

app.backend.base-url=http://localhost:7001

spring.cloud.gateway.server.webmvc.routes[0].id=backend-api
spring.cloud.gateway.server.webmvc.routes[0].uri=${app.backend.base-url}
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/**
