spring.application.name=travelwithai-backend-service
server.port=7001
spring.docker.compose.enabled=false

app.system.frontend-url=http://localhost:7002
app.gateway.name=travelwithai-api-gateway

app.storage.postgres.enabled=false
app.storage.redis.enabled=false
app.storage.vector.enabled=false

app.integrations.hotels.provider=mock
app.integrations.maps.provider=mock
app.integrations.payment.provider=mock

app.ai.default-model=mock-orchestrator
app.ai.memory-provider=vector-db
