spring.application.name=travelwithai-backend-service
server.port=7001
spring.docker.compose.enabled=false

app.system.frontend-url=http://localhost:7002
app.gateway.name=travelwithai-api-gateway

app.storage.postgres.enabled=${APP_STORAGE_POSTGRES_ENABLED:false}
app.storage.postgres.url=${APP_POSTGRES_URL:jdbc:postgresql://localhost:5432/travelwithai}
app.storage.postgres.username=${APP_POSTGRES_USER:travel_admin}
app.storage.postgres.password=${APP_POSTGRES_PASSWORD:travel_secret}
app.storage.redis.enabled=false
app.storage.vector.enabled=false

app.integrations.hotels.provider=mock
app.integrations.maps.provider=mock
app.integrations.payment.provider=mock

app.ai.default-model=mock-orchestrator
app.ai.memory-provider=vector-db


spring.datasource.url=${AUTH_DB_URL:jdbc:postgresql://localhost:5450/postgres}
spring.datasource.username=${AUTH_DB_USERNAME:postgres}
spring.datasource.password=${AUTH_DB_PASSWORD:root1234}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.default_schema=invest_platform_ai
